version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: ./infrastructure/backend/Dockerfile
    volumes:
      - ./backend/app/:/app/app/
  frontend:
    build:
      context: .
      dockerfile: ./infrastructure/frontend/Dockerfile
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000